AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  location-http-api

Globals:
  Function:
    Timeout: 3

Resources:

  TransmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transmit/
      Handler: receiver.receive
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ReceiveNMEASentence:
          Type: Api
          Properties:
            Path: /transmit
            Method: post
  
Outputs:
  TransmitApi:
    Description: "API Gateway endpoint URL for Prod stage for Transmit function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/transmit/"
  TransmitFunction:
    Description: "Transmit Lambda Function ARN"
    Value: !GetAtt TransmitFunction.Arn
  TransmitFunctionIamRole:
    Description: "Implicit IAM Role created for Transmit function"
    Value: !GetAtt TransmitFunctionRole.Arn

