AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  location-http-api

Globals:
  Function:
    Timeout: 60

Resources:

  ReceiveQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ReceiveQueue

  TransmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: transmit/
      Handler: receiver.receive
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          RECEIVE_QUEUE:
            !GetAtt ReceiveQueue.QueueName
      Events:
        ReceiveNMEASentence:
          Type: Api
          Properties:
            Path: /transmit
            Method: post
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sqs:*'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:sqs:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':'
                    - !GetAtt ReceiveQueue.QueueName            

Outputs:
  TransmitApi:
    Description: "API Gateway endpoint URL for Prod stage for Transmit function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/transmit/"
  TransmitFunction:
    Description: "Transmit Lambda Function ARN"
    Value: !GetAtt TransmitFunction.Arn
  TransmitFunctionIamRole:
    Description: "Implicit IAM Role created for Transmit function"
    Value: !GetAtt TransmitFunctionRole.Arn