AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  location-storage

Globals:
  Function:
    Timeout: 3

Resources:

  LocationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
        StreamSpecification:
            StreamViewType: KEYS_ONLY
        ProvisionedThroughput:
            WriteCapacityUnits: 1
            ReadCapacityUnits: 1
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        KeySchema:
            - KeyType: HASH
              AttributeName: id

  LocationProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: location-processor/
      Handler: processor.process_receive_queue
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment: 
        Variables:
          LOCATION_TABLE: 
            Ref: LocationTable
      Events:
        ReceiveQueueEvent:
          Type: SQS
          Properties:
           Queue: arn:aws:sqs:us-east-1:938211403396:ReceiveQueue
           BatchSize: 1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/'
                    - Ref: LocationTable

Outputs:
  LocationProcessorFunction:
    Description: "Location Processor Lambda Function ARN"
    Value: !GetAtt LocationProcessorFunction.Arn
  LocationProcessorFunctionIamRole:
    Description: "Implicit IAM Role created for Location Processor function"
    Value: !GetAtt LocationProcessorFunctionRole.Arn
