AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  location-storage

  Sample SAM Template for location-storage

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  LocationProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: location-processor/
      Handler: processor.process_receive_queue
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ReceiveQueueEvent:
          Type: SQS
          Properties:
           Queue: arn:aws:sqs:us-east-1:938211403396:ReceiveQueue
           BatchSize: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LocationProcessorFunction:
    Description: "Location Processor Lambda Function ARN"
    Value: !GetAtt LocationProcessorFunction.Arn
  LocationProcessorFunctionIamRole:
    Description: "Implicit IAM Role created for Location Processor function"
    Value: !GetAtt LocationProcessorFunctionRole.Arn
